CB-10704 transform the CCM connectivity error message to an understandable by the end user It is a common case when customers launch clusters with CCM enabled and it fails due to different networking issues. The error message that we prompt back to the user is not really understandable by them. If developers are looking at the error message they immediatelly know that the customer has connectivity issues, but it is not trivial to the customers. If we would provide a more clear message to them where the issue is they might can debug and fix the error themselves.
A typical error message look like this:
com.sequenceiq.environment.exception.FreeIpaOperationFailedException: FreeIpa creation operation failed. FreeIpa creation failed. Status: 'CREATE_FAILED' statusReason: 'Status: 502 Bad Gateway Response: {"status":502,"code":"cluster-proxy.ccm.endpoint-unavailable","message":"Unable to get endpoint from CCM for key (i-nstanceid, GATEWAY)"}'

Not to mention that we also expose Cloudera internal details. This error message is changed as part of this PR to:
The Control Plane was not able to establish the connection with the CM server instance. This means that the reverse SSH tunnel (autossh process) running on the instance could not connect to the Cloudera server. Please check your connection and proxy settings and make sure the instance can reach *.ccm.cdp.cloudera.com'

As part of this PR, the Salt bootstrap phase is also fixed in FreeIPA to make the flow step fail upon
failure and do not ignore it.