CB-6713 ensure that we have a temporary workaround for RELENG-9338. Unfortunately CM 7.2.0 has a hard dependency on postgresql10 and upgrading to 7.2.0 will just fail with the following yum error message:
      --> Processing Dependency: postgresql10-server >= 10 for package: cloudera-manager-server-db-2-7.2.0-2736107.el7.x86_64
      --> Finished Dependency Resolution
      Error: Package: cloudera-manager-server-db-2-7.2.0-2736107.el7.x86_64 (cloudera-manager)
                 Requires: postgresql10-server >= 10
       You could try using --skip-broken to work around the problem
       You could try running: rpm -Va --nofiles --nodigest |