CB-18174 Cloudbreak uses old Azure SDK that is relying on old nimbusds libraries, and therefore the cert based authentication failed with NoSuchMethodError.
 Main problem, that it looks like that:
  - com.nimbusds:oauth2-oidc-sdk:6.5
  - com.nimbusds:nimbus-jose-jwt:[6.0.1,) -> 9.23 are incompatible

  Solution is to update Azure SDK and Azure Client Auth version